// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StudentsAPIDbContext))]
    [Migration("20240423102507_DropFeeNameListTable")]
    partial class DropFeeNameListTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("API.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aca_Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Academic_Year");
                });

            modelBuilder.Entity("API.Models.ClassMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class_Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassMasters");
                });

            modelBuilder.Entity("API.Models.FeeMaster", b =>
                {
                    b.Property<int>("Fee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apply_For")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Due_Dates")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Each_Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fee_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Installment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Compulsary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Fee_Id");

                    b.ToTable("Fee_Master");
                });

            modelBuilder.Entity("API.Models.FeeNameList", b =>
                {
                    b.Property<int>("Fee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fee_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fee_Id");

                    b.ToTable("FeeNameList");
                });

            modelBuilder.Entity("API.Models.FeePerticular", b =>
                {
                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<double>("Admission_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Bus_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Comp_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("E_Learning_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Exam_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Gratuity_Fund")
                        .HasColumnType("REAL");

                    b.Property<double>("Hostel_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Lab_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Library")
                        .HasColumnType("REAL");

                    b.Property<double>("Library_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("PTA")
                        .HasColumnType("REAL");

                    b.Property<double>("Scout_Guide")
                        .HasColumnType("REAL");

                    b.Property<double>("Term_Fee")
                        .HasColumnType("REAL");

                    b.Property<double>("Tution_Fee")
                        .HasColumnType("REAL");

                    b.HasKey("Class");

                    b.ToTable("FeePerticulars");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Property<Guid>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Academic_Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adhaar_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Admission_Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Admission_No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Father_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gr_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother_Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Student_Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Student_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("API.Models.StudentData", b =>
                {
                    b.Property<Guid>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Academic_Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adhaar_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Admission_Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Admission_No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Father_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gr_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother_Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Student_Id");

                    b.ToTable("StudentsData");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
