// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StudentsAPIDbContext))]
    [Migration("20240412132102_AddFeeMasterTable")]
    partial class AddFeeMasterTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("API.Models.ClassMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class_Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassMasters");
                });

            modelBuilder.Entity("API.Models.FeeMaster", b =>
                {
                    b.Property<int>("Fee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apply_For")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Due_Dates")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Each_Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fee_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Installment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Compulsary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Fee_Id");

                    b.ToTable("Fee_Master");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Property<Guid>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Academic_Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adhaar_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Admission_Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Admission_No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Father_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gr_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother_Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Student_Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Student_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("API.Models.StudentData", b =>
                {
                    b.Property<Guid>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Academic_Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adhaar_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Admission_Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Admission_No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Father_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gr_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guardian_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother_Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Student_Id");

                    b.ToTable("StudentsData");
                });
#pragma warning restore 612, 618
        }
    }
}
